---
# Sub playbook to install all components needed.

- name: Apply common configuration to all nodes
  include: install-common.yml

- name: Set up Kerberos KDC
  include: install-kerberos.yml
  when: SECURITY_ENABLED == true

- name: Install Hadoop common components
  include: install-hadoop-core.yml

- name: Install zookeeper nodes
  include: install-zookeeper.yml

- name: Install HBase
  include: install-hbase.yml

- name: Install monitoring
  include: install-monitoring.yml
  when: MONITORING_ENABLED == true
