---
# Sub playbook to start all HBase services on the relevant machines

- hosts: hbase-master
  tasks:
    - name: Create HBase root directory in HDFS with privileged user
      include: ../roles/hbase/tasks/create-hbase-root.yml
      when: SECURITY_ENABLED == true

- hosts: workers
  tasks:
    - name: Start HBase region server
      service: name=hbase state=started

- hosts: cluster
  tasks:
    - name: Start HBase masters
      service: name=hbase state=started