---
# Sub playbook to start all Hadoop services on the relevant machines

- hosts: master-1
  tasks:
    - name: Start namenode
      service: name=namenode state=started

    - name: Start resourcemanager
      service: name=resourcemanager state=started

- hosts: workers
  tasks:
    - name: Start datanode
      service: name=datanode state=started

    - name: Start nodemanager
      service: name=nodemanager state=started
