---
# Sub playbook to stop all Hadoop services on the relevant machines

- hosts: master-1
  tasks:
    - name: Stop namenode
      service: name=namenode state=stopped

    - name: Stop resourcemanager
      service: name=resourcemanager state=stopped

- hosts: workers
  tasks:
    - name: Stop datanode
      service: name=datanode state=stopped

    - name: Stop nodemanager
      service: name=nodemanager state=stopped
