---
# Sub playbook to stop all HBase services on the relevant machines

- hosts: workers
  tasks:
    - name: Stop HBase regionserver
      service: name=hbase state=stopped

- hosts: cluster
  tasks:
    - name: Stop HBase masters
      service: name=hbase state=stopped