---
# Sub playbook to install all common components needed.

- name: Set up Kerberos KDC
  hosts: kdc_server
  roles:
    - { role: kdc-server, when: SECURITY_ENABLED == true }

- name: Install Kerberos Clients
  hosts: cluster
  roles:
    - { role: krb-client, when: SECURITY_ENABLED == true }

- name: Apply common configuration to all nodes
  hosts: all

  roles:
    - { role: goozbach.EPEL, when: ansible_os_family == 'RedHat' }
    - common

- name: Install zookeeper nodes
  hosts: zookeepers
  roles:
    - zookeeper

- name: Install Hbase
  hosts: cluster
  roles:
    - hbase
